### ISSUE TITLE
error in finalise-promotion-step (`len(releases) != len(flavours)`)

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/glci-legacy#10]
**What happened**:

Releasing Garden Linux `934.1`, the process got stuck in the `finalise-promotion-step` in the `promote-gardenlinux-task` with the following error message:

```
Found: len(releases)=7
Expected: len(flavours)=12
release was not complete - will not publish (this indicates a bug!)
```

To make matters worse, the pipeline, even though literally indicating a bug, [did not abort]((https://github.com/gardenlinux/glci/blob/99425c4bf67b74eb71301dbc23d149fc28faa9b8/ci/steps/promote_step.py#L146)) but tried to (unsuccessfully) finish anyway.

**What you expected to happen**:

1. No error in the release process.
1. Pipeline aborts if it literally indicates a bug.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

The error was caused by the [flavours.yaml](https://github.com/gardenlinux/glci/blob/main/flavours.yaml) in the [gardenlinux/glci](https://github.com/gardenlinux/glci) which contains 12 flavours for the flavour-set `all`. However, as five of the flavour combinations in that file are not for public clouds but for bare-metal, their release manifests were missing.

I already took the liberty to [introduce](https://github.com/gardenlinux/gardenlinux/pull/1396) a `gardener` flavour-set into the `flavours.yaml` in [gardenlinux/gardenlinux](https://github.com/gardenlinux/gardenlinux) which only contains the public cloud builds. It should be considered just targeting that flavour set even though it might require some additional alignment whether this approach is desirable.

**Comment by ccwienk** [comment]
@MrBatschner : I think this bug should hopefully be implcitly closed through recent overhaul / re-implementation of publishing gear

**Comment by MrBatschner** [comment]
No longer relevant.
