### ISSUE TITLE
Manifest misses published_image_metadata 

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/glci-legacy#20]
**What happened**:

Some generated release manifests contain `published_image_metadata: null`, instead of the required information to retrieve the image ID. 

Found the `published_image_metadata` missing in the following Versions:
- all 934.10 
- 934.9 arm64 images

**What you expected to happen**:

`published_image_metadata` should contain information about how the image is named on the published cloud platform.
The naming and the structure of that value in `published_image_metadata` depends on the cloud platform.

E.g. for azure it should contain a `urn`, and for gcp it should contain a `gcp_image_name`.  

**How to reproduce it (as minimally and precisely as possible)**:
Example for 934.10:
https://s3.console.aws.amazon.com/s3/object/gardenlinux-github-releases?region=eu-central-1&prefix=meta/singles/azure-gardener_prod-amd64-934.10-f057c9b

Example for 934.9 arm64:
https://s3.console.aws.amazon.com/s3/object/gardenlinux-github-releases?region=eu-central-1&prefix=meta/singles/azure-gardener_prod-arm64-934.9-54c63e5

**Anything else we need to know**:

Why is this relevant? I want to generate the image ids and paste them on the github release page of gardenlinux.
 
To be more precise, I want to write a pipeline for that - but currently my manual process is also not working, since it is based on parsing the manifest file.

**Comment by MrBatschner** [comment]
This is caused by the nightly job in Garden Linux overwriting the manifest with empty values each time it runs - i.e. every night. It is not a problem of the glci publishing gear.
/close
