### ISSUE TITLE
Ensure that Garden Linux is properly published for Gen2

### ISSUE THREAD

**Issue by nanory** [gardenlinux/glci-legacy#22]
**What would you like to be added**:
Due to gardenlinux/gardenlinux#1189, we know that Garden Linux  works with Gen2 Azure instances but we must ensure that we properly publish these Azure images for both generations (there is a difference between them).

**Why is this needed**:
To fully support Gen2

**Comment by gehoern** [comment]
@MrBatschner i think this is already done, isn't it?

**Comment by MrBatschner** [comment]
This is implemented for publishing to community image galleries in https://github.com/gardenlinux/glci/pull/11, but not for publishing through Azure Marketplace.
This issue should be moved to [glci](https://github.com/gardenlinux/glci/issues) as the code base no longer lives in the main Garden Linux (i.e. this) repo.

**Comment by Vincinator** [comment]
@MrBatschner done - moved to gardenlinux/glci

**Comment by MrBatschner** [comment]
Fixed/Implemented with https://github.com/gardenlinux/glci/pull/11.
