### ISSUE TITLE
Default path of gardenlinux/builder seems a bit strage

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/glci-legacy#59]
[Here](https://github.com/gardenlinux/glci/blob/e8cb95a58ec9241314ef07f9eaf110eb1c988c98/paths.py#L20) it is assumed that https://github.com/gardenlinux/builder is cloned to a dir `gardenlinux-builder`. But git's default is to call the clone dir like the repo name, so it's more likely to have a directory called `builder` in that place.

Maybe we could just check for both, not sure if this might introduce a regression for anyone relying on the old behaviour.

**Comment by MrBatschner** [comment]
Reason for that is that if you maintain a fairly flat directory hierarchy on your filesystem (like the author of that particular piece of code), `builder` is not really a descriptive name for a directory, hence the `gardenlinux-` prefix. 
However, your remark absolutely makes sense and the default directory can always be overridden with the env variable `GARDENLINUX_BUILDER_PATH`. Feel free to change it but keep in mind that several pipeline definitions not hosted in this repository/org might need to be altered too.
