### ISSUE TITLE
enhance glci to incrementally upload to converge cloud, skip if image already exists

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/glci-legacy#73]

**Comment by Vincinator** [comment]
Moved from GL issue board (Draft issue) to glci, because @ccwienk is helping us and taking over this issue.

**Comment by pnpavlov** [comment]
@MrBatschner & @pnpavlov to align by 20th if this is still required or handled with latest changes.

**Comment by pnpavlov** [comment]
Problem not reproducable in last two runs, we will reopen if needed.
